### ISSUE TITLE
Lightweight builder (without `attrs`)

### ISSUE THREAD

**Issue by turansky** [JetBrains/kotlin-wrappers#1000]
### Plan
- [x] Add `ChildrenBuilder` - #1034
- [x] Add `FC` factory method - #1034
- [x] Update examples
- [x] Move non-builder logic in `kotlin-react-core` subproject - #1039
- [x] Move `RBuilder` related logic in `kotlin-react-legacy` and `kotlin-react-dom-legacy` subprojects - #1057
- [x] Release `pre.282` with new subproject structure
