### ISSUE TITLE
Kotlin DSL

### ISSUE THREAD

**Issue by turansky** [JetBrains/kotlin-wrappers#161]
### Problem
* No navigation for main extensions (`configurePublishingWithNPM` for example)
* No navigation for task (`compileKotlinJs` for example)
* Poor syntax highlight

### Plan
- [x] Standard plugin configuration for `Kotlin/JS` plugin (#160)
- [x] Versions in `gradle.properties` (#163)
- [x] Publish extensions/plugins (NPM, Maven)
  * Preparing (#164, #165)
  * Replace `configurePublishing` (#166)
  * Replace `configurePublishingWithNPM` (#167)
- [x] Groovy -> Kotlin DSL (#168)
- [x] Apply Kotlin DSL extensions (#168)

Target branch - `1.4-js-ir`

**Comment by turansky** [comment]
@Leonya Looks like #91 can be closed too :)
