### ISSUE TITLE
NPM publications

### ISSUE THREAD

**Issue by turansky** [JetBrains/kotlin-wrappers#201]
1. Are they used?
2. Empty `kotlin-css-js`. Is it expected?
3. `kotlin-css-jvm` in NPM? Is it error?

Plan:
- [x] Remove `:kotlin-css:kotlin-css-jvm` (#202)
- [x] Remove `:kotlin-css:kotlin-css-js` (#203)
- [x] Fix publishing for `@jetbrains/kotlin-css` (#204)
- [x] Fix `package.json` constructing (#205, #206)
- [x] Cleanup NPM publications (#207)

**Comment by Leonya** [comment]
> Are they used?

Yes, they are used by create-react-kotlin-app

> Empty kotlin-css-js. Is it expected?

It should not be empty, try installing the `@jetbrains/kotlin-css-js` npm package.

> kotlin-css-jvm

Ideally, it shouldn't be there.

**Comment by turansky** [comment]
> It should not be empty, try installing the @jetbrains/kotlin-css-js npm package.

I will check it. Look like publication correction required

> Ideally, it shouldn't be there. 

Can it (`kotlin-css-jvm`) be removed at all?

**Comment by Leonya** [comment]
> Can it (kotlin-css-jvm) be removed at all?

There is no need to publish it to NPM, but it can't be removed completely.

**Comment by turansky** [comment]
Subroject `:kotlin-css:kotlin-css-jvm` create NPM publication only, isn't it?

**Comment by Leonya** [comment]
What do you mean? There's https://bintray.com/kotlin/kotlin-js-wrappers/kotlin-css-jvm

**Comment by turansky** [comment]
> There's https://bintray.com/kotlin/kotlin-js-wrappers/kotlin-css-jvm

It's published by `:kotlin-css` subproject

**Comment by Leonya** [comment]
OK, then I guess it's not needed.

**Comment by turansky** [comment]
@Leonya FYI - `produceExecutable()` doesn't work as expected on `kotlin-wrappers` now. Errors in IR
