### ISSUE TITLE
Autogenerated package.json

### ISSUE THREAD

**Issue by turansky** [JetBrains/kotlin-wrappers#214]
- [x] `description` & `author` in `gradle.properties` (#215)
- [x] Remain `peerDependencies` only in `package.json` template (#217)
- [x] Remove project dependencies from `package.json` template (#220)
- [x] Declare NPM dependencies in Gradle scripts (#223)
- [x] Calculate `peerDependencies` automatically (#223)

**Comment by Leonya** [comment]
Released in pre.98
